version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.839.0
    - 2.841.0
    - 2.889.0
    - 2.893.0
  - dependency-name: aws-cdk
    versions:
    - 1.99.0
