name: Clean Up Pull Request Stack

on:
  pull_request:
    types: [closed]

env:
  CACHE_VERSION: 0
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1
  AWS_DEFAULT_REGION: eu-west-1

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          version: 12
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Set ENVIRONMENT
        run: echo "::set-env name=ENVIRONMENT::PullRequest$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
      - name: Destroy pull request test stack
        run: yarn cdk destroy --force
